version: "3"

services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - "./postgres-cfg.env"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    env_file:
      - "./pgadmin-cfg.env"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: